spring:
  application:
    name: spring-kafka-app
  docker:
    compose:
      enabled: true
      file: docker-compose-redpanda.yaml
  kafka:
    bootstrap-servers: localhost:19092
    streams:
      bootstrap-servers: localhost:19092
      application-id: word-counter-stream

  cloud:
    function:
      definition: wordProcess
    stream:
      kafka:
        binder:
          brokers: localhost:19092
        streams:
          binder:
            application-id: spring-cloud-app
      bindings:
        wordProcess-in-0:
          destination: input-word-process
        wordProcess-out-0:
          destination: output-word-process




