spring:
  docker:
    compose:
      enabled: true
  kafka:
    streams:
      application-id: stream-app-java
      bootstrap-servers: localhost:19092
      replication-factor: 1

    consumer:
      group-id: stream-apps

server:
  port: 9090
management:
  dynatrace:
    metrics:
      export:
        enabled: false
